export const NavigationConfig = [{
  key: 'home',
  title: 'Home',
  url: '#home'
}, {
  key: 'services',
  title: 'Services',
  url: '#services'
}, {
  key: 'story',
  title: 'About',
  url: '#story'
}, {
  key: 'career',
  title: 'Projects',
  url: '#career'
}, {
  key: 'partners',
  title: 'Partners',
  url: '#partners'
}, {
  key: 'team',
  title: 'Team',
  url: '#team'
}, {
  key: 'contact',
  title: 'Contact',
  url: '#contact'
}]
